### PR TITLE
Add room number: bug fix

### LINKED ISSUE #36: add room number
We should add room-number to initial-values of `RegisterForm` after this property will be handled by backend endpoint

### PR DESCRIPTION
**Pull request by LucasBywalec**
Related work item: GH-36

closes: #36

### CODE REVIEW

File: src/components/RegisterForm/RegisterForm.tsx [hunk 1]
```diff
@@ -33,20 +41,25 @@ export function RegisterForm() {
 
   const minLength = 1;
   const { t } = useTranslation();
-  const validate = (values: CreateUserType) => {
-    const errors: CreateUserType = {};
+  const validate = (values: CreateUserError) => {
+    let errors = {} as CreateUserError;
```
Comment (kaczor6418) [inline src/components/RegisterForm/RegisterForm.tsx:45]: not true. `{}` !== `CreateUserError`

File: src/components/RegisterForm/RegisterForm.tsx [hunk 2]
```diff
@@ -33,20 +41,25 @@ export function RegisterForm() {
...
+
     if (values.email === undefined || values.email.length < minLength) {
-      errors.email = t('registerForm.emailEmpty');
+      errors = { ...errors, email: t('registerForm.emailEmpty') };
```
Comment (kaczor6418) [inline src/components/RegisterForm/RegisterForm.tsx:48]: why not just `errors.email = t('registerForm.emailEmpty')`. There is no need to create a copy of the whole object
(same comment to all below examples)

**Review by kaczor6418 — CHANGES_REQUESTED** [review]

File: src/components/RegisterForm/RegisterForm.tsx [hunk 3]
```diff
@@ -15,9 +16,33 @@ export function RegisterForm() {
...
+    }
+
+    for (const key of keys) {
+      if (!(key in record)) {
+        return false;
+      }
+    }
+
+    return true;
+  }
```
Comment (kaczor6418) [inline src/components/RegisterForm/RegisterForm.tsx:31]: This is a helper function. Please put this inside the appropriate directory
https://github.com/dorm-social-room-manager/dsrm-frontend/wiki/Project-structure#srccommonutils

File: src/components/RegisterForm/RegisterForm.tsx [hunk 4]
```diff
@@ -33,20 +58,26 @@ export function RegisterForm() {
 
   const minLength = 1;
   const { t } = useTranslation();
-  const validate = (values: CreateUserType) => {
-    const errors: CreateUserType = {};
+  const validate = (values: CreateUserError) => {
+    isRecordWithAllFields<CreateUserError>(values, ['email', 'password', 'name', 'surname', 'roomNumber']);
```
Comment (kaczor6418) [inline src/components/RegisterForm/RegisterForm.tsx:62]: why are you calling this function here? It doesn't change anything

**Review by kaczor6418 — CHANGES_REQUESTED** [review]

**Review by kaczor6418 — DISMISSED** [review]
LGTM :sunglasses:
